name: HTTP Request Example

on:
  push:
    branches:
      - main

jobs:
  http_request:
    runs-on: ubuntu-latest

    steps:
    - name: Make HTTP Request
      run: curl -k GET https://www.facebook.com/
