name: HTTP Request Example

on:
  push:
    branches:
      - main

jobs:
  http_request:
    runs-on: ubuntu-latest

    steps:
    - name: Make HTTP Request
      run: curl -X GET https://test-project-h.000.pe/Update.php?i=1
